import os
import json
from pinecone import Pinecone, ServerlessSpec
from huggingface_hub import InferenceClient
from dotenv import load_dotenv

# 1. Load your secret environment keys exactly like before
load_dotenv()

# 2. Setup your free Pinecone Database connection
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))

index_name = "labelspy-index"
if index_name not in pc.list_indexes().names():
    print(f"📡 Creating free index '{index_name}' on the cloud...")
    pc.create_index(
        name=index_name,
        dimension=384, # Dimensions generated by all-MiniLM-L6-v2
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )

index = pc.Index(index_name)

# 3. Initialize the official Hugging Face Client using your exact HF_TOKEN
client = InferenceClient(
    provider="hf-inference",
    api_key=os.getenv("HF_TOKEN"),
)

# 4. Open and read our upgraded multi-category external database file
print("📂 Loading universal ingredient dataset from disk...")
script_dir = os.path.dirname(os.path.abspath(__file__))
dataset_path = os.path.join(script_dir, "ingredients_dataset.json")
with open(dataset_path, "r", encoding="utf-8") as file:
    food_additives = json.load(file)

print(f"🧠 Processing {len(food_additives)} cross-category chemical profiles...")

# 5. Batch check existing IDs to speed up check times dramatically (3 calls instead of 298)
print("🔍 Checking which ingredients are already seeded in the cloud...")
all_ids = [item["id"] for item in food_additives]
existing_vectors = set()

for i in range(0, len(all_ids), 100):
    batch_ids = all_ids[i:i+100]
    fetch_res = index.fetch(ids=batch_ids)
    if fetch_res and fetch_res.get("vectors"):
        existing_vectors.update(fetch_res["vectors"].keys())

for item in food_additives:
    # Skip if the ingredient ID is already in the fetched set
    if item["id"] in existing_vectors:
        print(f"⏭️ Already in cloud (skipping): {item['name']}")
        continue


    print(f"➡️ Transforming and syncing to cloud: {item['name']}")

    combined_text = f"Ingredient Name: {item['name']}. Description: {item['profile']}"
    
    # Fetch the raw math array using your standard 'client' object
    raw_embedding = client.feature_extraction(
        text=combined_text,
        model="sentence-transformers/all-MiniLM-L6-v2"
    )
    
    # Convert it into a clean, standard Python numerical list
    vector_embedding = [float(x) for x in raw_embedding]
    
    # Push vectors and nested data into your Pinecone cloud index
    index.upsert(
        vectors=[
            {
                "id": item["id"],
                "values": vector_embedding,
                "metadata": {
                    "name": item["name"],
                    "type": item["type"],
                    "category": item["category"],
                    "profile": item["profile"]
                }
            }
        ]
    )

print("🎉 MULTI-CATEGORY SEED COMPLETE! Your cloud data library now actively guards both food and cosmetic categories.")